### ISSUE TITLE
This is great but some ideas for fixes/improvements:

### ISSUE THREAD

**Issue by Masono03** [MaiRiosIPla/unshittify-discord#2]
- Server icons should be bigger and become semi square when viewing a server like OldCord
- Search bar isnt working unless you click the magnifying glass.
- When using vencord, the top right box overlaps the Quick Toolbox
- When resizing the Channel list it cuts off/breaks the User Modal

**Comment by Xaero252** [comment]
Can confirm the 2nd. Not quite sure why, you can click very far to the left or on the magnifying glass and the keyboard focus will work but otherwise keyboard focus will not shift to the search bar.

**Comment by khatharsis42** [comment]
100% agreed, there should be a way to make the server icons bigger !

**Comment by CSNelson7** [comment]
search bar definitely needs to be fixed, its really not great

**Comment by MaiRiosIPla** [comment]
The search bar is now fixed thanks to [AlexPetrenko1](https://github.com/AlexPetrenko1)

**Comment by MaiRiosIPla** [comment]
Some more fixes have been implmented:
- Rounded server icons now become square when selected (see example pic)
- Fixed resizing of the Channel list. (see before and after pics)

![Image](https://github.com/user-attachments/assets/759d88cc-3217-491c-871a-89e00d7e7d83)

![Image](https://github.com/user-attachments/assets/c234b4fe-a2d6-423f-9a00-cd689dbf2e57)
![Image](https://github.com/user-attachments/assets/9afbc262-80c9-4a02-9a6f-5d528ca34be0)

**Comment by Masono03** [comment]
> Also, I just realized some changes to scale the server icons slipped into the commit, just know those don't do anything right now.
> 
> [@Masono03](https://github.com/Masono03) About the Vencord Quick Toolbox, it's a tradeoff. Since Discord regularly adds or removes icons to the bar, fixing the toolbox icon to a specific location would make it cover up other things. What I'm getting at is that to fix that issue, we introduce many others. Also, the icon is only covered up when the window is small, and expanding it makes it visible again. So it's a very specific issue I personally don't think most people would have.
> 
> Remember that regardless of my opinion, you are free to modify the CSS, (or maybe not, according to the DC TOS, but you get what I'm saying), have a go at positioning the toolbox icon where you find it most convenient!

Thats understandable. I was just listing stuff i found just in case. I have a question regarding those icosn at the top right tho what is the leftmost supposed to do? The one with the 2 boxes and arrows? i cant click it at  all prolly  because of the toolbox overlap. Also i noticed without the top bar its impossible to move discord bewteen screens with drag and drop (without hotkeys) so i was wondering  if we ccould get a very very thin top bar or that funcction included somewhere else

**Comment by Masono03** [comment]
> Some more fixes have been implmented:
> 
> * Rounded server icons now become square when selected (see example pic)
> * Fixed resizing of the Channel list. (see before and after pics)
> 
> ![Image](https://github.com/user-attachments/assets/759d88cc-3217-491c-871a-89e00d7e7d83)
> 
> ![Image](https://github.com/user-attachments/assets/c234b4fe-a2d6-423f-9a00-cd689dbf2e57) ![Image](https://github.com/user-attachments/assets/9afbc262-80c9-4a02-9a6f-5d528ca34be0)

User Modal still fails to keep the icons for me and doesnt resize as it should (video)
Also something that wasnt there before todays update: The + on the text bar is way too much left (picture)


![Image](https://github.com/user-attachments/assets/3eb07569-a7c3-47d1-86de-8cee15dfba89)
https://github.com/user-attachments/assets/542a021b-9a2a-44fd-9dbe-2391245425be

**Comment by xnovaq** [comment]
Excellent improvements. 
Apparently, the "drag window" icon doesn't work for me any more, neither the old one I used to run nor the live online one. Could we somehow define areas of the regular top bar to drag around the window, as it used to be possible? That icon solution is the one aspect I don't like very much, tbh. Otherwise, this is the version they should've shipped in the first place!

**Comment by MaiRiosIPla** [comment]
@Masono03 idk how themes are refreshed, but maybe yours hasn't updated? Also, the small icon is where the drag functionality is. I was going to explain a bit in depth why making the whole top draggable was not possible, and in doing so I realized it might be.

**Comment by MaiRiosIPla** [comment]
Now the window is dragged by clicking close to the top of the window (+ a tiny tweaks)

**Comment by Masono03** [comment]
> [@Masono03](https://github.com/Masono03) idk how themes are refreshed, but maybe yours hasn't updated? Also, the small icon is where the drag functionality is. I was going to explain a bit in depth why making the whole top draggable was not possible, and in doing so I realized it might be.

so i think whats causing mine to still not format might be the "gaming" button thats a vencord plugin to quickly disable gaming activity. idk if that something you can somehow fix or if it would be down to the plugin creator to fix.

**Comment by xnovaq** [comment]
> Now the window is dragged by clicking close to the top of the window (+ tiny tweaks) [@xnovaq](https://github.com/xnovaq)
> 
> ![Image](https://github.com/user-attachments/assets/d0bc4f4b-1e89-4e9e-a3d7-8514da390717)

Turned out perfect. Thank you! 

> > [@Masono03](https://github.com/Masono03) so i think whats causing mine to still not format might be the "gaming" button thats a vencord plugin to quickly disable gaming activity. idk if that something you can somehow fix or if it would be down to the plugin creator to fix.

I also run that plugin and my formatting is correct. Do you have any other theme still loaded?

**Comment by Masono03** [comment]
> > Now the window is dragged by clicking close to the top of the window (+ tiny tweaks) [@xnovaq](https://github.com/xnovaq)
> > ![Image](https://github.com/user-attachments/assets/d0bc4f4b-1e89-4e9e-a3d7-8514da390717)
> 
> Turned out perfect. Thank you!
> 
> > > [@Masono03](https://github.com/Masono03) so i think whats causing mine to still not format might be the "gaming" button thats a vencord plugin to quickly disable gaming activity. idk if that something you can somehow fix or if it would be down to the plugin creator to fix.
> 
> I also run that plugin and my formatting is correct. Do you have any other theme still loaded?

Nope no other theme and i tried turnning off any plugin that changes something in that Modal but it still has the same behavior as in that video i sent. i also reloaded it by now by taking it out of the load refreshing discord and putting it back in to ensure im on latest version (which i am since i can drag anywhere at the top) but nope still does it

**Comment by Xaero252** [comment]
```
.trailing_c38106:not(:hover) > :not(.winButtons_c38106){
	display: none;
}

.trailing_c38106:not(:hover) .winButtonsWithDivider_c38106::before{
	display: none;
}
```

Here's an interesting idea for the toolbox covering up elements when the window width is too narrow. Basically this will hide the Inbox, Help, and Update icons in the toolbox and leave the minimize, maximize, and close buttons present. When hovering over the toolbox it will expand. Could wrap it with appropriate media query (ex: `@media all and (max-width: 1280px)`) to make it only behave this way if the window is too small.

Preview:

https://github.com/user-attachments/assets/5813d386-feb0-4358-b54f-8da433adaa59

**Comment by MaiRiosIPla** [comment]
@Xaero252 love it, but it would have to be an option.

**Comment by CSNelson7** [comment]
Something I've noticed, when I have a discord nitro theme active there's a spot at the bottom left that doesn't have it applied, leaving an ugly grey rectangle
any chance this can be fixed?

![Image](https://github.com/user-attachments/assets/d3f4fd4e-5c25-4d75-9a8f-8a2c37f209ee)

**Comment by halflen** [comment]
another minor issue 

![Image](https://github.com/user-attachments/assets/2a66e3ae-4cea-49d9-9a50-b8e35603da03)

the view channel updates in your server option is misaligned.
